name: automerge
on: pull_request
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
    - uses: KeisukeYamashita/auto-pull-request-merge@v1
    - run: echo "nothing to see here"
      with:
        intervalSeconds: 10
        timeoutSeconds: 30
